security:
  basic:
      enabled: false

google:
    client:
      clientId: 736431198769-bp5ucng54khib2ss568ogmv835jhu14l.apps.googleusercontent.com
      clientSecret: 7p4mURq8uTRO_yMG-AIpFU6z
      accessTokenUri: https://www.googleapis.com/oauth2/v4/token
      userAuthorizationUri: https://accounts.google.com/o/oauth2/v2/auth
      clientAuthenticationScheme: form
      tokenName: oauth_token
      authenticationScheme: query
      scope:  
            - openid
            - profile
            - email
    resource:
      userInfoUri: https://www.googleapis.com/oauth2/v2/userinfo

github:
  client:
    clientId: bd1c0a783ccdd1c9b9e4
    clientSecret: 1a9030fbca47a5b2c28e92f19050bb77824b5ad1
    accessTokenUri: https://github.com/login/oauth/access_token
    userAuthorizationUri: https://github.com/login/oauth/authorize
    clientAuthenticationScheme: form
  resource:
    userInfoUri: https://api.github.com/user

logging:
  level:
    org.springframework.security: DEBUG
 
server:
  port: 8080
 
spring:
  profiles:
    active: "dev"
  server:
    port: 8080
       
